### ISSUE TITLE
failure in processing random test

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/grmpy#162]
```
seed =  4178
np.random.seed(seed)

dict_ = generate_random_dict()
print_dict(dict_)
simulate('test.grmpy.ini')
fit('test.grmpy.ini')


Traceback (most recent call last):
  File "run.py", line 22, in <module>
    fit('test.grmpy.ini')
  File "/home/peisenha/external_storage/ownCloud/office/workspace/OpenSourceEconomics/grmpy/grmpy/estimate/estimate.py", line 33, in fit
    check_init_file(dict_)
  File "/home/peisenha/external_storage/ownCloud/office/workspace/OpenSourceEconomics/grmpy/grmpy/check/check.py", line 66, in check_init_file
    raise UserError(msg)
grmpy.check.custom_exceptions.UserError: 

         The distributional characteristics have to be undeterministic.
```

**Comment by peisenha** [comment]
... withdraw as I now understand
